version: "3.9"
services:
  db:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '3306:3306'
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'mylara-db:/var/lib/mysql'
volumes:
  mylara-db:
    driver: local
