#!/usr/bin/env bash

chown www-data:www-data /var/www
chmod 755 /var/www

chown www-data:www-data /var/www/html
chmod 755 /var/www/html

chown -R www-data:www-data /var/www/html/public
chmod -R 755 /var/www/html/public

chown -R www-data:www-data /var/www/html/storage
chmod -R 777 /var/www/html/storage

service php8.2-fpm restart
service nginx restart
# npm run dev
tail -f /dev/null
